version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: docker-resources/Dockerfile_Local
    ports:
      - "5000:5000"
    links:
      - "db:db"
    env_file:
      - docker-resources/env/app.env
    volumes:
      - "./:/code"
    command: ["gunicorn", "--workers=2", "--threads=4", "--worker-class=gthread", "--bind", "0.0.0.0:5000", "index:app"]
  db:
    image: postgres
    env_file:
      - docker-resources/env/db.env
    ports:
      - "5432:5432"
    volumes:
      - ~/Dev/doubloon:/var/lib/postgresql/data