version: "3.3"
services:
  web:
    build:
      context: .
    ports:
      - "5000:5000"
    links:
      - "db:db"
    env_file:
      - app.env
    volumes:
      - ./:/code
    command: ["python", "-m", "flask", "run"]
  db:
    image: postgres
    environment:
      - POSTGRES_DB=doubloon_admin
      - POSTGRES_USER=sayre
      - POSTGRES_PASSWORD=Yohomie#88
    ports:
      - "5432:5432"
    volumes:
      - ~/Dev/doubloon:/var/lib/postgresql/data